# PROBLEM TWO
# https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def find_sum_of_even_fibs():
    fibs = [1,2]
    i = 1
    while (fibs[i] + fibs[i-1]) < 4000000:
        fibs.append(fibs[i] + fibs[i-1])
        i += 1
    return sum([x for x in fibs if is_even(x)])

def is_even(num):
    return not(num % 2)

print 'the sum of even-valued fibonacci numbers under 1 million is ' + str(find_sum_of_even_fibs())